# The URL the site will be built for
base_url = "https://divinci.ai"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Enable taxonomies
taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

# Default language used in the site
default_language = "en"

# The site title and description; used in feeds by default
title = "Divinci AI"
description = "Empowering human-AI collaboration with custom AI solutions"

# The default author for pages
[extra.author]
name = "Divinci Team"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "dracula"
smart_punctuation = true

[extra]
# Put all your custom variables here
copyright = "© 2023-2025 Divinci AI. All rights reserved."
