#!/usr/bin/env python3
"""Generate the Agent Skills discovery index from the SKILL.md files on disk.

The Agent Skills Discovery spec (v0.2.0) requires a sha256 `digest` for every
skill artifact. A hand-written digest is wrong the moment anyone edits a skill,
and nothing at request time would notice — the index would simply advertise a
hash that does not match the file it points at. So the index is generated, and
`src/agent-skills-index.mjs` is build output rather than source.

Runs ahead of `zola build` (see the build command in site/wrangler.jsonc).

The `description` for each skill comes from the SKILL.md front matter, so the
index and the artifact can never disagree about what a skill is for.
"""

import hashlib
import json
import pathlib
import re
import sys

SITE = pathlib.Path(__file__).resolve().parent.parent
SKILLS_DIR = SITE / "static" / ".well-known" / "agent-skills"
OUT_MJS = SITE / "src" / "agent-skills-index.mjs"

SCHEMA = "https://schemas.agentskills.io/discovery/0.2.0/schema.json"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def front_matter(text: str) -> dict:
    """Parse the leading `---` YAML block. Only flat `key: value` is supported,
    which is all a SKILL.md header needs — pulling in a YAML dependency for
    three keys is not worth the build-time cost."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    out = {}
    for line in text[3:end].splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def main() -> int:
    if not SKILLS_DIR.is_dir():
        print(f"[agent-skills] no {SKILLS_DIR}, nothing to do")
        return 0

    skills = []
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        name = skill_md.parent.name
        raw = skill_md.read_bytes()
        meta = front_matter(raw.decode("utf-8"))

        description = meta.get("description", "").strip()
        if not description:
            print(f"[agent-skills] ERROR: {name}/SKILL.md has no `description` "
                  f"in its front matter — the index requires one.")
            return 1
        if not NAME_RE.match(name):
            print(f"[agent-skills] ERROR: directory name {name!r} is not a valid "
                  f"skill id (lowercase alphanumeric and hyphens).")
            return 1

        skills.append({
            "name": name,
            "type": "skill-md",
            "description": description,
            # Relative URL: the same index is served from staging and
            # production, and an absolute divinci.ai URL on staging would send
            # agents to the wrong host.
            "url": f"/.well-known/agent-skills/{name}/SKILL.md",
            "digest": "sha256:" + hashlib.sha256(raw).hexdigest(),
        })

    if not skills:
        print(f"[agent-skills] ERROR: {SKILLS_DIR} exists but contains no "
              f"*/SKILL.md files. The scanner treats an empty `skills` array "
              f"as a failure, so this is never what you want.")
        return 1

    index = {"$schema": SCHEMA, "skills": skills}

    OUT_MJS.write_text(
        "// GENERATED by scripts/build-agent-skills.py — do not edit.\n"
        "// Source of truth: static/.well-known/agent-skills/*/SKILL.md\n"
        "export const SKILLS_INDEX = "
        + json.dumps(index, indent=2)
        + ";\n"
    )

    print(f"[agent-skills] indexed {len(skills)} skill(s): "
          + ", ".join(s["name"] for s in skills))
    return 0


if __name__ == "__main__":
    sys.exit(main())
